apiVersion: v1
kind: Service
metadata:
  name: {{ include "kidscare-owner-backoffice.fullname" . }}
  labels:
{{ include "kidscare-owner-backoffice.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "kidscare-owner-backoffice.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
