{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kidscare-owner-backoffice.serviceAccountName" . }}
  labels:
{{ include "kidscare-owner-backoffice.labels" . | indent 4 }}
{{- end -}}
